### ISSUE TITLE
Support wallet v2  apis / auth so we can login as market-sim parties into console

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega-market-sim#200]
Support wallet v2  apis / auth so we can login as market-sim parties into console.

Console now uses the wallet v2 api(s) which means we cannot use the current setup to login to the console as one of the agents we created :-( . Let's fix that; it's very useful ;-).

**Comment by TomMcL** [comment]
Blocked by https://github.com/vegaprotocol/vega/issues/6819
