### ISSUE TITLE
Market sim bots overnight run (separate from the RL one)

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega-market-sim#346]
Let's think about how to re-purpose @cdummett's work on "creating markets generating lot of data" into overnight fuzzing runs. 

At the moment the RL sim repeatedly creates a market, trades, settles. 

We should try 
- running something where the market(s) run for ~ 12 hours wall time (whatever that means in simulated time). 
- throw as many of the bots as we reasonably can onto the market.
- they can share underlying price sources which can be anything that's pre-downloaded and saved (so we don't report failures just because data didn't get downloaded); we could e.g. download a few weeks worth of data, then start at a random point and if we get to the end then simply reverse and head backwards (or jump to the beginning - this would potentially create a nice hefty jump). 
- it should use @TomMcL's visualisation so that we can see what kind of markets a successful run produced.

**Comment by davidsiska-vega** [comment]
@cdummett do we have anything like a "degen agent class"? I.e. a party that gets some money, makes a directional trade using about 80-90% of their balance and then sits on it till it's closed out? We may want to throw a few of those in here.

Also at least one of the markets we're running this on should allow stupid leverage like 150x.

**Comment by cdummett** [comment]
> @cdummett do we have anything like a "degen agent class"? I.e. a party that gets some money, makes a directional trade using about 80-90% of their balance and then sits on it till it's closed out? We may want to throw a few of those in here.

Nice will add a few of those and make sure they enter their positions at different times. I'm guessing we would want to "grow" the position if they profit from M2M?

> Also at least one of the markets we're running this on should allow stupid leverage like 150x.

I was thinking of fuzzing the market governance proposals as well; perhaps 1x "normal" market, 1x "risky" market, and then n fuzzed markets (@davidsiska-vega).

**Comment by davidsiska-vega** [comment]
Closed by https://github.com/vegaprotocol/vega-market-sim/pull/347 .
