### ISSUE TITLE
Add on-chain trading rewards to fuzzing run

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega-market-sim#400]
The on-chain rewards are specified here:
- https://github.com/vegaprotocol/specs/blob/master/protocol/0056-REWA-rewards_overview.md 

For vega market sim in the fuzzing run:
- check epoch length parameter and set to "sensible" value (some rewards come once per epoch)
- create and faucet new assets (possibly one per reward type so it's easy to track who's got how much from which reward scheme) and send them to a new type of "reward funding agent"
- make sure the assets have economically meaningful quantum for what they are matching the asset DPs, set `rewards.marketCreationQuantumMultiple` to a "realistic" value
- fund reward accounts for "Market activity (fee based) reward metrics":
1. Sum of maker fees paid by the party on the market this epoch
1. Sum of maker fees received by the party on the market this epoch
1. Sum of LP fees received by the party on the market this epoch 
- fund "Market creation reward"
- add plot of balances in the relevant accounts for parties expecting to be rewarded; ideally together with activities they are rewarded for (so we can visually confirm these are mostly in line).

**Comment by barnabee** [comment]
Things we might want fuzzing params/ranges to test:
- extremely assymetric payouts (one or two parties getting almost eveything, potentially many others with almost nothing)
- account topping up transfers runs low so either small transfer of crumbs or no transfer on some epoch, what happens that epoch and next
- no party accrues any rewards for a given epoch
- …
