### ISSUE TITLE
Add Network History Segment comparison to market sims tests

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega-market-sim#406]
To try and capture non-deterministic behaviour across core/datanode we would like to compare the network segments produced by nightly market sims test. The test should compare the segments produced by 2 datanodes connected to seperated core nodes.

**Comment by gordsport** [comment]
Created here and moved from:
- https://github.com/vegaprotocol/system-tests/issues/2088

**Comment by davidsiska-vega** [comment]
We would need a capsule setup that runs a number of nodes; say 3...
