### ISSUE TITLE
The units on PnL numbers look suspicious... 

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega-market-sim#567]
... are we converting to the wrong DPs somewhere?

<img width="531" alt="image" src="https://github.com/vegaprotocol/vega-market-sim/assets/62546419/ed4719b7-c5e7-4137-9d8d-c2bb3986feb9">

**Comment by cdummett** [comment]
Closing as datanode no longer reports profit and loss for the network. Profit and loss values validated in core feature tests.
