### ISSUE TITLE
Update market sim to work with new asset bridge

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega-market-sim#624]
The work on the new asset bridge has got to the point that its now running on CI see branch: [epic/arbitrum](https://github.com/vegaprotocol/vega/tree/epic/arbitrum). However, this is failing on the market-sim runs.

Its thought that now we need to specify a chain ID for an asset proposal the market sim needs to be updated to work with this new process.

**Comment by cdummett** [comment]
Closing as no market-sim work needed for new bridge.
