### ISSUE TITLE
Add functionality allowing running of testnet bots on vega-market-sim

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega-market-sim#96]
We generally want to improve testnet bots. There are two directions to tackle this in:
1) develop good bots in vega-market-sim and then make them run on testnet
2) run testnet bots on vega-market-sim and try for some quick wins. 

This issue is about 2). Once we're able to do this people can easily play with testnet bot parameters / logic to see what effect changing them is likely to have before deploying to testnet and disrupting things there.

**Comment by TomMcL** [comment]
Probably not worth the time at this stage
